import './App.css';
import img1 from './Images/bomb.png';
import img2 from './Images/police.png';
import img3 from './Images/run.png'; 


function App() {
  return (
    <div >
      <div class="body1">
        <div class="left">
          <p>"All the News That's Fit to Print"</p>
        </div>
        <div class="middle">
          <p>The New York Times</p>
        </div>
        <div class="right">
          <center><h4>Late Edition</h4></center>
          <p class="small">New York:Today,sunny a few afternoon clouds.High 27,<b>Tonight</b> silghtly more humid.Low 65 <b>Tommorow</b>,sun then clouds. High 81 <b>Yesterday</b> high 83,low 63. Weather map, Page C18. </p>
        </div>
        </div>
        <div class="line1">
        </div>
        <span class="same1">VOL.CL..No.51,874</span>
        <span class="same2">copyright @2002 The New York Times</span>
        <span class="same1">NEW YORK,WEDNESDAY,SEPTEMBER 12,2001</span>
        <span class="same2">81 beyond guided New York 89273</span>
        <span class="same1">75 CENTS</span>
        <div class="line2">
        <center>
          <p class="mainhead">U.S. ATTACKED</p>
          <hr></hr>
        </center>
        <p class="subhead"><b>HIJAKED JETS DESTROY TWIN TOWERS AND HIT PENTAGON IN DAY OF TERROR</b></p>
        </div>
        <div class="one">
          <center><p><b>A CREEPING HORROR</b></p></center>
          <p class="small"> 
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm 
          <br></br> 
          vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm 
          <br></br>vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi <br></br>sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv <br></br> hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm<br></br> vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs <br></br> vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h</p>
        </div>

        <div class="two">
            <table>
            <tr><img class="img1" src={img1} alt="Nothing"></img></tr>
            <tr><img class="img2" src={img2} alt="Nothing"></img></tr>
            </table>
            <div class="img3">
            <img class="short1" src={img3} alt="Nothing"></img>
            </div>
            <div class="img4">
            <img class="short2" src={img3} alt="Nothing"></img>
            </div>
        </div>
        <div class="three">
          <center><p><b>PRESIDENT VOWS TO EXACT PUNISHMENT FOR EVIL</b></p></center>
          <p class="small">
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h</p>
        </div> 
        <br></br>
        <p class="small" >
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h
          hbdhaf jksrbvifhbsa hvblirsv chjuvc l ,HJGLAIURgvbUGSHBVYLGkjhugb ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, hhbdhaf jksrbvifhbsa hvblirsv chjuvc l ivhbf viuvj j,f vliusv  hib ihs dvj ;ikflihhv hbvdsv j k cj is vhkbvs vbs usbdvn nb idbv  fbj, cvadhk vb bjvgsdc bndhvcsn dbc.khsvd  hk.hda ,hjbcba vkdbvkabckj.bvis dcbm vklsdhbc;usbvn hjbvi sfn bsvb, h</p>
    </div>
  );
}

export default App;
